# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20190825_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '审核失败'), (1, '审核中'), (0, '审核通过')], default=1, verbose_name='状态'),
        ),
    ]
