# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-26 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_auto_20190825_1538'),
        ('talks', '0007_auto_20190825_1606'),
    ]

    operations = [
    ]
