# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_merge_20190826_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '审核通过'), (-1, '审核失败'), (1, '审核中')], default=1, verbose_name='状态'),
        ),
    ]
