# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0014_auto_20190828_1856'),
        ('talks', '0013_auto_20190827_2240'),
    ]

    operations = [
    ]
